import { describe, expect, test } from "bun:test";
import { join } from "node:path";
import { minioClient } from "@/config/minio";

// Helper function to poll MinIO until the background worker uploads the optimized file
async function pollForProcessedObject(
  bucket: string,
  key: string,
  maxAttempts = 15,
): Promise<any> {
  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      return await minioClient.statObject(bucket, key);
    } catch (error) {
      if (attempt === maxAttempts) {
        throw new Error(
          `Pipeline timeout: File ${key} was not generated by the worker.`,
        );
      }

      await new Promise((resolve) => setTimeout(resolve, 500));
    }
  }
}

describe("Image Optimization Pipeline E2E", () => {
  test("should process a raw upload, trigger the worker via queue, and emit an optimized webp file", async () => {
    const id = Bun.randomUUIDv7();
    const bucketName = "public";
    const rawKey = `${id}/original.png`;
    const optimizedKey = `${id}/optimized.webp`;

    await minioClient.fPutObject(
      bucketName,
      rawKey,
      join(import.meta.dir, "../fixtures/fun.png"),
      {
        "Content-Type": "image/png",
        "Optimize-Image": "true",
        quality: "80",
        width: "1920",
        "output-object-key": optimizedKey,
      },
    );

    const optimizedStat = await pollForProcessedObject(
      bucketName,
      optimizedKey,
    );

    expect(optimizedStat).toBeDefined();
    expect(optimizedStat.size).toBeGreaterThan(0);
  }, 12000);
});
